project:
  type: website
  output-dir: _site
format:
  html:
    theme: litera
    toc: true
    toc-location: right
    self-contained: true
website:
  title: "Farhan Sadeek"
  site-url: https://academic.farhansadeek.com
  navbar:
    left: 
      - text: "Professional"
        href: https://farhansadeek.com
        icon: "fa-briefcase"
      - text: "Notes"
        href: https://notes.farhansadeek.com
        icon: "fa-book"
      - text: "Photography"
        href: https://photos.farhansadeek.com
        icon: "fa-camera"
    right:
      - icon: twitter-x
        href: https://twitter.com/SadeekFarhan21
      - icon: linkedin
        href: https://www.linkedin.com/in/farhansadeek/
      - icon: envelope
        href: mailto:sadeekfarhan21@gmail.com
      - icon: github
        href: https://github.com/SadeekFarhan21
        