project:
  type: website
  output-dir: _site
format:
  html:
    theme: litera
    toc: true
    toc-location: right
    self-contained: true
website:
  title: "Farhan Sadeek"
  site-url: https://academic.farhansadeek.com
  repo-url: https://github.com/SadeekFarhan21/academic.farhansadeek.com
  navbar:
    left:
      - text: "Website"
        menu: 
          - text: "Professional"
            href: https://farhansaadeek.com
          - text: "Notes"
            href: https://notes.farhansaadeek.com
          - text: "Photography"
            href: https://photos.farhansaadeek.com
      - text: "Links"
        menu:
        - text: "Github"
          href: https://github.com/SadeekFarhan21
        - text: "Linkedin"
        - text: "Twitter"
        - text: "Tableau"